# Generated by Django 3.1.4 on 2021-02-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policeemergency',
            name='date',
        ),
    ]
