# Generated by Django 3.1.4 on 2021-02-19 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pgs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usertype', models.CharField(blank=True, choices=[('B', 'BOYS'), ('G', 'GIRLS'), ('O', 'BOTH')], max_length=250, null=True)),
                ('kitchen_available', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=250, null=True)),
                ('washroom_attached', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=250, null=True)),
                ('laundry_included', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=250, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('locality', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
