# Generated by Django 3.1.4 on 2021-02-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgs',
            name='roomtype',
            field=models.CharField(blank=True, choices=[('1', 'SINGLE SEATER'), ('2', 'DOUBLE SEATER'), ('3', 'THREE SEATER')], max_length=250, null=True),
        ),
    ]
