# Generated by Django 3.1.7 on 2021-02-19 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pg', '0002_pgs_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgs',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pgs',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
