# Generated by Django 3.1.7 on 2021-02-20 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('pay', models.IntegerField(blank=True, null=True)),
                ('skillsrequired', models.TextField(blank=True, null=True)),
                ('minimumdesignation', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('jobtype', models.CharField(blank=True, choices=[('P', 'Part time'), ('F', 'Full time')], max_length=250, null=True)),
                ('workfromhome', models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=250, null=True)),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
