# Generated by Django 3.1.4 on 2021-02-19 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('pay', models.IntegerField(blank=True, null=True)),
                ('skillsrequired', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
