# Generated by Django 3.1.7 on 2021-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='jobtype',
            field=models.CharField(blank=True, choices=[('P', 'Part time'), ('F', 'Full time')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='minimumdesignation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='workfromhome',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=250, null=True),
        ),
    ]
